# -*- coding: utf-8 -*-
"""
Created on Wed Jul 29 15:16:24 2015
Euler Project, Problem 44
"""

#pentagonal numbers are generated by Pn=n(3n−1)/2.
#the first ten pentagonal numbers are: 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

#it can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
#however, their difference, 70 − 22 = 48, is not pentagonal.

#find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal 
#and D = |Pk − Pj| is minimised; what is the value of D?


from datetime import datetime
t1=datetime.now()

def search(n):
    for i in range(1,n):
        for j in range(i+1,n):
            p1 = 0.5*i*(3*i-1)
            p2 = 0.5*j*(3*j-1)
            psum = p1+p2
            ptst = (0.5+(.25+6*psum)**0.5)/3
            if ptst % 1 == 0:
                pdif = p2-p1
                ptst = (0.5+(.25+6*pdif)**0.5)/3
                if ptst % 1 == 0:
                    return pdif
                
pdif = search(10000)                                
print pdif

t2=datetime.now()
print '\nElapsed time:', t2-t1